### ISSUE TITLE
Add a more informative description of what `point` and `vector` functions do.

### ISSUE THREAD

**Issue by LukaHorvat** [ekmett/linear#100]
Just a slight documentation change. By now I've had to look at the source 3 times to see which one sets `w` to 0 and which one sets it to 1.

I kind of get that a vector is translation invariant so it's `w` is 0, but there's no reason not to make this a bit more obvious in the documentation. Right?

**Comment by acowley** [comment]
Does that PR help?

**Comment by LukaHorvat** [comment]
Yes, great!
