### ISSUE TITLE
Make the `instance Dim n => Trace (V n)` in `Linear.Trace` polykinded

### ISSUE THREAD

**Issue by harpocrates** [ekmett/linear#121]
As it stands, this instance is present in `Linear.Trace` which does not have `PolyKinds` enabled, which means that I get the following surprising interaction

    ghci> :set -XOverloadedLists -XDataKinds
    ghci> import Linear
    ghci> import Linear.V
    ghci> Just v = fromVector [1..5] :: Maybe (V 5 Double)
    ghci> trace (outer v v)
    <interactive>:5:1: error:
        • No instance for (Trace (V 5)) arising from a use of ‘trace’
        • In the expression: trace (outer v v)
          In an equation for ‘it’: it = trace (outer v v)

One can easily get around this by enabling `PolyKinds` and redeclaring the instance `instance Dim n => Trace (V n)`. The fix should be pretty simple: add the following at the top of `src/Linear/Trace.hs`:

```
#if __GLASGOW_HASKELL__ >= 707
{-# LANGUAGE PolyKinds #-}
#endif
```

I can make a pull request if you'd like, but the fix seems so small. :)

**Comment by bgamari** [comment]
Alec Theriault <notifications@github.com> writes:

> As it stands, this instance is present in `Linear.Trace` which does not have `PolyKinds` enabled, which means that I get the following surprising interaction
>
>     ghci> :set -XOverloadedLists -XDataKinds
>     ghci> import Linear
>     ghci> import Linear.V
>     ghci> Just v = fromVector [1..5] :: Maybe (V 5 Double)
>     ghci> trace (outer v v)
>     <interactive>:5:1: error:
>         • No instance for (Trace (V 5)) arising from a use of ‘trace’
>         • In the expression: trace (outer v v)
>           In an equation for ‘it’: it = trace (outer v v)
>
> One can easily get around this by enabling `PolyKinds` and redeclaring the instance `instance Dim n => Trace (V n)`. The fix should be pretty simple: add the following at the top of `src/Linear/Trace.hs`:
>
> ```
> #if __GLASGOW_HASKELL__ >= 707
> {-# LANGUAGE PolyKinds #-}
> #endif
> ```
>
> I can make a pull request if you'd like, but the fix seems so small. :)
>     
A pull request will certainly speed things up.
