### ISSUE TITLE
Conversion between V0..V4 and V n

### ISSUE THREAD

**Issue by Laar** [ekmett/linear#123]
I'm constructing V n for fixed n <= 4, which currently needs to go through a function similar to
```
f a1 a2 a3 = fromJust . fromVector . V.fromList $ [a1 a2 a3]
```
Which I find rather ugly due to the fromJust. It would be nice if there were conversions between the fixed size vectors (`V0 a` .. `V4 a`) and the 'dynamic' sized vector `V n a`. The construction of low order `V n` could then be written as 
```
f a1 a2 a3 = toV $ V3 a1 a2 a3 
```

**Comment by ekmett** [comment]
Maybe a class w/ a class associated type family for the dimension and conversions back/forth maybe as an iso?

**Comment by ekmett** [comment]
```haskell
class Finite v where
  type Size v :: k -- this kind needing to be polymorphic may force Size to not be a class associated type but just a type family?
  _V :: Iso (V n a) (V n b) (v a) (v b) 
```

would let you construct a V 4 a from V4 a using

`_V # V4 a b c d`

and convert back by matching with `^._V`

**Comment by ekmett** [comment]
A `default` could be supplied using Foldable and Monad or something like that.

**Comment by ekmett** [comment]
That maybe should be done a bit differently so that the _V iso can convert to different vector types?

**Comment by ekmett** [comment]
That would let you convert from V 4 a -> V 3 a  by using stuff like

```haskell
over _V (\(V4 a b c d) -> V3 a b c) :: V 4 a -> V 3 a
```

**Comment by ekmett** [comment]
Done!
