### ISSUE TITLE
Incorrect quaternion exponentiation

### ISSUE THREAD

**Issue by wyager** [ekmett/linear#126]
Try the following in GHCi:

```hs
import Linear.Quaternion
import Linear.V3
earthRotSecond = axisAngle (V3 0 0 1) (2*pi/(60*60*24))
earthRotSecond
earthRotSecond ** 1
```

What's going on here? It's returning almost exactly `sqrt(1/2) + k sqrt(1/2)`. Is there some sort of numerical error when the rotation angle is small? It's not *that* small, only around 3.6e-5.

**Comment by wyager** [comment]
Got it. Looks like the exponentiation algorithm was wrong. Maybe slipped notice because it's close to correct for many values. Will submit a PR shortly.

**Comment by ekmett** [comment]
I'll have to check against my original source for the quaternion algorithm. Some stuff got shuffled around incorporating early herbie results that may not be correct, and or I may have simply fat fingered some of the tricky cases around infinities, etc.

**Comment by ekmett** [comment]
Merged.
