### ISSUE TITLE
Why is Point Additive?

### ISSUE THREAD

**Issue by sattlerc** [ekmett/linear#128]
I thought the point of Point was to forget about the origin. As such, the following instances feel wrong: Additive, Metric, Epsilon. One could also say something about Num, Fractional, etc.

When naively trying to write a - b for the vector between points a and b, I would rather have an error that then leads me to find a .-. b rather than an unjustified success that leads me to write unP (a - b).

**Comment by RyanGlScott** [comment]
See https://github.com/ekmett/linear/issues/111.

**Comment by sattlerc** [comment]
Thanks. Wouldn't lerp make more sense as an inhabitant of Affine?
