### ISSUE TITLE
Cabal 2.0 compatible release on hackage

### ISSUE THREAD

**Issue by niteria** [ekmett/linear#129]
b577da663927a2cc613ce0bd1ecc10c3b168cede makes this library work with GHC 8.2 and Cabal 2.0, but it's not part of any release yet.

Can you make a release on hackage?

FWIW the testsuite passes with GHC 8.2.

**Comment by phadej** [comment]
Have to remove `Warning.hs` before that (and modify `Setup.lhs`)

**Comment by niteria** [comment]
Can you elaborate?
`Warning.hs` was just added with b577da663927a2cc613ce0bd1ecc10c3b168cede.
Is it bad/broken? I thought `Setup.lhs` was also fixed as part of that commit.

**Comment by phadej** [comment]
@niteria it's not broken, but https://github.com/phadej/cabal-doctest/blob/master/example/Setup.hs is "better".

**Comment by niteria** [comment]
I see, would it help if I started sending pull requests to the affected packages?

**Comment by phadej** [comment]
@niteria that would be great!

**Comment by niteria** [comment]
My mistake, it works if I don't unnecessarily try to install Cabal-2.0.0.0 in the same sandbox.
The only package that didn't work for me was `log-domain`, the rest already have a working `cabal-doctest` fix.
