### ISSUE TITLE
Constant vectors in Linear.V

### ISSUE THREAD

**Issue by jachymb** [ekmett/linear#130]
I would find it useful to have a function like this

    constV :: forall a n. KnownNat n => a -> V n a

which creates a vector of given (type-level) length with some default value.
It can be implemented quite easily:

    constV = fromJust . fromVector . replicate (reflectDim (Proxy :: Proxy n))

but I find this somewhat ugly due to the use of `fromJust`. It would be nicer to have a library function which does not need this.

**Comment by cchalmers** [comment]
Your `constV` is simply [`pure`](https://github.com/ekmett/linear/blob/master/src/Linear/V.hs#L270).

**Comment by glguy** [comment]
The fix for this would be to add documentation somewhere explaining how to use the library.
