### ISSUE TITLE
R1..R4 instances for Quaternion?

### ISSUE THREAD

**Issue by cpdurham** [ekmett/linear#131]
Been playing around with porting some shadertoy examples and was curious if there's a reason Quaternion doesn't have R instances.

**Comment by ekmett** [comment]
This is doable. The main "weirdness" is you probably want the scalar part to be w here, so that x y z correspond to the vector part.

**Comment by ekmett** [comment]
We do have `Field` instances, so you can use _1, _2, _3 and _4 to access the parts.
