### ISSUE TITLE
Add Monoid instance for Linear.V

### ISSUE THREAD

**Issue by jachymb** [ekmett/linear#132]
The obvious definition:

```
instance (Dim n, Monoid m) => Monoid (V n m) where
    mempty = pure mempty
    mappend = liftA2 mappend
```

Would be nice to also have semigroup instance of course.

**Comment by RyanGlScott** [comment]
I'd hesitate to call this instance "obvious". `V` behaves like a [`ZipList`](http://hackage.haskell.org/package/base-4.10.0.0/docs/Control-Applicative.html#t:ZipList) in its `Applicative` instance, and there's still an [ongoing debate](https://mail.haskell.org/pipermail/libraries/2015-July/026039.html) on what the ideal `Semigroup`/`Monoid` instance for `ZipList` should be. I think we should resolve that debate first, and then adapt `V` to have `Semigroup`/`Monoid` instances which mirror those for `ZipList`.
```

**Comment by phadej** [comment]
@RyanGlScott `V` cannot change it's length. So the `liftA2` instance is obvious from the two of `ZipList` instances.

For the record, none of V1, V2 etc have those either, but should be added if we proceed with `V`.

**Comment by RyanGlScott** [comment]
@phadej, good point about the static length. In that case, there really isn't a debate to be had here!

In light of this, I'd happily welcome a PR adding `Semigroup`/`Monoid` instances for the various `V` types in `linear`.

**Comment by ekmett** [comment]
This is the only possible instance. No objection here.

**Comment by jachymb** [comment]
similar instance could be added for `Alternative` btw.

**Comment by tysonzero** [comment]
`Alternative` does not allow for the needed `Monoid m` constraint.

**Comment by ekmett** [comment]
Added in 6e11214
