### ISSUE TITLE
Add Integral instance for Linear.V

### ISSUE THREAD

**Issue by jachymb** [ekmett/linear#133]
Add Integral instance for Linear.V the same way Numeric instance is defined.

**Comment by phadej** [comment]
For the record, none of `V1`, `V2` etc have those. (for `Monoid` and `Semigroup`)

But for `Integral`, is's difficult as 

```
class (Real a, Enum a) => Integral a where
```

and we cannot make `V` an `Enum`.

**Comment by jachymb** [comment]
Ah, I see. Originally, I simply wanted to be able to use '(^)' elementwise conveniently, but it is `Integral` in second parameter. I see that making instances for `Enum` and `Real` would be awkward at best. My apologies for not remembering the constraints initially.

**Comment by phadej** [comment]
no worries

**Comment by ekmett** [comment]
This is not implementable.
