### ISSUE TITLE
Need `Num a` for instances of `Complicated`/`Hamiltonian` for sparse datatypes

### ISSUE THREAD

**Issue by sjoerdvisscher** [ekmett/linear#139]
F.e. when a sparse value does not contain a value for `i`, the `_i` lens should return `0`, but that is not possible since `_i` has no `Num a` constraint:

    _i :: Lens' (t a) a

Or am I missing something?

**Comment by ekmett** [comment]
All of the classes we have for R1..Rn, Complicated, Hamiltonian, etc. currently assume the data type is dense.

Do you have a practical application for small sparse data types?

**Comment by sjoerdvisscher** [comment]
I'm toying with geometric algebra: https://gist.github.com/sjoerdvisscher/01e813c1f2bf48f4eb82537ddacd81fe

**Comment by ekmett** [comment]
That would do it. =) I can bring myself to accept a patch that adds Num constraints to R1..Rn, Complex, Hamiltonian, etc. if you need it.

**Comment by sjoerdvisscher** [comment]
Sadly this isn't going to work. This would require `E` to get a `Num` constraint too, but then it can't be used anymore as a `Representable` `Key`.
