### ISSUE TITLE
Random instance for Linear.V

### ISSUE THREAD

**Issue by bmabsout** [ekmett/linear#140]
Any reason why there's no random instance? this works for me: 
```haskell
instance (Dim n,Random m) => Random (V n m) where
    random = runState $ sequence (pure (state random))
    randomR (a,b) = runState $ sequence $ fmap state $ liftA2 (curry randomR) a b
```

**Comment by Taneb** [comment]
I presume you mean the `Random` in `System.Random`? That lives in the `random` package, which currently `linear` doesn't (directly) depend on.

**Comment by bmabsout** [comment]
yes from System.Random, it's a pretty useful instance though...

**Comment by ekmett** [comment]
Added in 98e3ddf as we have incurred an indirect dependency via `vector` anyways.
