### ISSUE TITLE
lerp interpolates the wrong way?

### ISSUE THREAD

**Issue by gilgamec** [ekmett/linear#164]
I guess I've never had occasion to use it, but I just noticed that `lerp` (in `Additive`) works the opposite way of any other lerp implementation I've seen. (A brief Googling supports this; see [C++](https://en.cppreference.com/w/cpp/numeric/lerp), [GLSL](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/mix.xhtml), [Unity](https://docs.unity3d.com/ScriptReference/Vector3.Lerp.html), [Processing](https://processing.org/reference/lerp_.html).) I'd expect that

    lerp t a b = a + t * (b - a);

that is, that `lerp 0 a b == a` and `lerp 1 a b == b`, and that is the case in all other implementations. However, the implementation in `linear` is the opposite of this, i.e. `lerp 0 a b == b` and `lerp 1 a b == a`.

Is this mismatch intentional? If so, can it be clearly documented? If not, might it be fixed? I understand that it's longstanding at this point, but maybe something can be done.

**Comment by RyanGlScott** [comment]
I agree that this is a bit counterintuitive. Moreover, the `slerp` function uses the opposite convention, where `slerp a b 0 = a` and `slerp a b 1 = b`.

Unfortunately, the `lerp` function is pretty widely used, so I'd feel a bit remorseful about changing the convention all of a sudden. I'd say the best thing to do is to just document this.

**Comment by mrehayden1** [comment]
Agreed. I was getting some very jittery animations until I figured this one out.

**Comment by mrehayden1** [comment]
Agreed. Can this not be made much clearer in the documentation?

I had some very jittery animations until I figured this out. It defies all my intuition to defined it this way!

**Comment by ekmett** [comment]
This was a complete brainfart on my part. I'm surprised it has stood this long.

**Comment by ekmett** [comment]
I'd be open to a major version bump and clear CHANGELOG entry and fixing this.

**Comment by RyanGlScott** [comment]
I've uploaded [`linear-1.23`](https://hackage.haskell.org/package/linear-1.23) to Hackage with a fix.
