### ISSUE TITLE
compilation broken with `random-1.2.1`

### ISSUE THREAD

**Issue by byorgey** [ekmett/linear#166]
`linear-1.21.6` no longer compiles for me with the recently released `random-1.2.1`:
```
[ 7 of 22] Compiling Linear.V         ( src/Linear/V.hs, dist/build/Linear/V.o, dist/build/Linear/V.dyn_o )

src/Linear/V.hs:147:10: error:
    Ambiguous occurrence ‘Finite’
    It could refer to
       either ‘System.Random.Finite’,
              imported from ‘System.Random’ at src/Linear/V.hs:132:1-20
              (and originally defined in ‘random-1.2.1:System.Random.GFinite’)
           or ‘Linear.V.Finite’, defined at src/Linear/V.hs:140:1
    |
147 | instance Finite Complex where
    |          ^^^^^^
```
I guess `random` added some new exports and `Linear.V` is importing `System.Random` unqualified.

**Comment by RyanGlScott** [comment]
Thanks for the bug report. I have uploaded [`linear-1.21.7`](https://hackage.haskell.org/package/linear-1.21.7) with a fix, and I have also revised the affected Hackage versions of `linear` such that they pick build plans with `random < 1.2.1`.
