### ISSUE TITLE
Why is `_Point` an `Iso'`, rather than a type-changing `Iso`?

### ISSUE THREAD

**Issue by ocharles** [ekmett/linear#171]
Is there any reason `_Point` can't change the type of vector-space? Naturally we can't change the dimensions, but changing the underlying element type?

**Comment by RyanGlScott** [comment]
(I've transferred this issue to `linear`, since I think that was the intended repo to open the issue against.)

**Comment by ocharles** [comment]
Whoops, not sure how that happened! Thanks.

**Comment by RyanGlScott** [comment]
As far as the question raised in the issue goes, this package does seem to have a convention of using simple `Lens`es and `Iso`s everywhere. I'm not sure if this is a deliberate choice or just a coincidence, however—I'd have to let someone more familiar with the history of the library chime in.

**Comment by ocharles** [comment]
@ekmett Could I get your input here? I just ran into this again wanting to write:

```haskell
over _Point (view _xy)
```

but that doesn't type check. Using `over coerced (view _xy)` doesn't work here because `coerced` is too general.

**Comment by ekmett** [comment]
I think there was an example where the type change caused some inference pain, but it was super early on when the combinators for extracting from a lens was too polymorphic, so I think it'd be fine to change to an Iso.

**Comment by ocharles** [comment]
Cool I'll open a PR
