### ISSUE TITLE
Triangular matrices

### ISSUE THREAD

**Issue by yongqli** [ekmett/linear#59]
Is there a good way of dealing with triangular matrices in a type-safe way? It would be nice to represent a triangular matrix as a vector of vectors of increasing length -- [V1, V2, V3], etc. But how would the types work?

**Comment by phaazon** [comment]
It would be something like `(V1,V2,V3)`.

**Comment by ekmett** [comment]
Right now things like triangular, block diagonal, etc. are pretty much out of scope of the package as it is currently designed.
