### ISSUE TITLE
Get ASetter for a Vector

### ISSUE THREAD

**Issue by yongqli** [ekmett/linear#60]
How can I enumerate the setters for a vector?

    set _x (V2 0 0 :: V2 Double) 9 :: V2 Double

 works

    let x = V2 9 9 :: V2 Double
    tabulate (\i -> Rep.index x i) :: V2 Double

works

but

    > tabulate (\i -> set i (0 :: V2 Int) x) :: V2 (V2 Int)

    <interactive>:93:21:
        Couldn't match type ‘E V2’
                      with ‘(a0 -> Identity (V2 Int)) -> V2 Int -> Identity (V2 Int)’
        Expected type: ASetter (V2 Int) (V2 Int) a0 (V2 Int)
          Actual type: Rep V2
        In the first argument of ‘set’, namely ‘i’
        In the expression: set i (0 :: V2 Int) x

Is there a way to enumerate the ASetters for a lens the way we can enumerate the viewing indices? 

I want a function that will give me all the `_x`, `_y`, etc automatically.

**Comment by glguy** [comment]
Note: http://hackage.haskell.org/package/linear-1.16.1/docs/Linear-Vector.html#v:E
````haskell
newtype E t = E { el :: forall x. Lens' (t x) x }
````
so your last example is either
````haskell
> tabulate (\(E i) -> set i 0 x) :: M22 Int
> tabulate (\i -> set (el i) 0 x) :: M22 Int
````
I don't know if that helps your final question, but it helps your code compile.

**Comment by yongqli** [comment]
Awesome, thanks!
