### ISSUE TITLE
Performance of a few functions (mkTransformation and scaled)

### ISSUE THREAD

**Issue by phaazon** [ekmett/linear#62]
# Context

I’m building a realtime 3D engine. That’s quite logical that I use `linear` for my linear algebra stuff then.

I’ve been experiencing a few framerate drops, so I profiled my application pretty quite intensively to find out the bug. I’m not sure it’s related to my FPS drops, but I’ve found something pretty weird about a few `linear`’s functions.
# Allocation profile

The first thing weird is that `mkTransformation` and `scaled` appear as top functions that consume the more memory. [Here is a header of my starting profile report](http://lpaste.net/119553). As you can see, `mkTransformation` and `scaled` eats up to 50% of the memory (and `omniProjViews` also has a high impact, I’ll check that later).

[Here’s a better context of a use of both the functions](http://lpaste.net/119554). As you can see, `mkTransformation` and `scaled` are responsible of a **lot** of memory consumption.
# Tuning the functions

What I did is pretty simple. I rewrote both the function to see if it was better. After having performed another profile, I [got this](http://lpaste.net/119556). `scaled` has totally disappeared and `mkTransformation` eats less memory, even though it still consumes a bit (`fromQuaternion` implementation, I guess).

[Here’s a better point of view](http://lpaste.net/119557).

Now, I can write a patch if you think it’s worth it. The implementation of my own functions is [here](http://lpaste.net/119558). Straight-forward implementation ;)

**Comment by glguy** [comment]
Function using this combination of choices and traverse do not optimize well. We should definitely reconsider, even if it means that the constraints on the function change slightly.

**Comment by glguy** [comment]
Could you please see if this helps?

**Comment by phaazon** [comment]
Sure, I will. Just for the record, `INLINABLE`? What’s the difference with `INLINE`?

**Comment by glguy** [comment]
Inlinable makes it possible to inline this function across module boundaries, but doesn't require it. It's also possible to use a SPECIALIZE pragma with an inlinable function. It's possible that INLINE would be appropriate, but INLINABLE is more conservative.

https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/pragmas.html#inlinable-pragma

**Comment by phaazon** [comment]
Thanks for the hint ;) I’m gonna test your changes right now then.

**Comment by phaazon** [comment]
It’s okay for `scaled`, but `mkTransformation` still swallows 10% of memory :(

**Comment by ekmett** [comment]
Unfortunately the lpaste links have bitrotted. =/

Closing as at least somewhat improved (50% -> 10%). `mkTransformationMat` could perhaps be improved by just manually writing it all the way out rather than letting it rely on that internal `snoc3` thing.

Please re-open if you can dredge up metrics.
