### ISSUE TITLE
No Floating instances

### ISSUE THREAD

**Issue by yongqli** [ekmett/linear#63]
Any particular reason or did no one get around to it yet?

**Comment by yongqli** [comment]
Well, I guess it's actually not that useful, since you can just use `fmap` for all of them. In case it's useful to anyone, the instance definitions are straightforward:

    instance Floating a => Floating (V4 a) where
      pi = pure pi
      exp = fmap exp
      log = fmap exp
      sin = fmap sin
      cos = fmap cos
      asin = fmap asin
      atan = fmap atan
      acos = fmap acos
      sinh = fmap sinh
      cosh = fmap cosh
      asinh = fmap asinh
      acosh = fmap acosh
      atanh = fmap atanh

**Comment by ekmett** [comment]
Yeah, those should be added.

**Comment by ekmett** [comment]
Fixed.
