### ISSUE TITLE
Too many constraints when trying to be generic over vectors

### ISSUE THREAD

**Issue by yongqli** [ekmett/linear#64]
I'm having a problem where trying to write functions that are generic in which vector type to use (`V0`, `V1`, `V2`, etc), the constraints explode. For example:

    storeInV :: (Applicative v, Unbox (v Int), Unbox (v Double), Unbox (v String), 
                 Num (v Int), Num (v Double))
             => Int -> (VU.Vector (v Int), VU.Vector (v Double), VU.Vector (v String))
    storeInV n =
      let
        x = VU.replicate n 1
        y = VU.replicate n 2
        z = VU.replicate n (pure "a")
      in (x, y, z)

If I have a function that calls `storeInV`, it has to "inherit" all of the constraints. All those constraints quickly become unmanageable.

I see two ways to solve this problem:
1) Find some way to express in Haskell the idea of a "Unboxing" container `v` such that any `Unbox a` implies `Unbox (v a)`. Perhaps the `constraints` package can help, but I don't know how to use it.

2) Somehow unify all `V0`, `V1`, etc under a single type, `Vn`. Perhaps a closed type family or something. We write an `Unbox` instance for `Vn`, and then the type signature for the above can simply be:

    storeInV :: Int -> (VU.Vector (Vn dim Int), VU.Vector (Vn dim Double), VU.Vector (Vn dim String))

I would be interested in working on this, but I don't know enough about advanced Haskell type system topics to know how to proceed. Could someone can point me to the relevant resources?

**Comment by ekmett** [comment]
FWIW- You're going to have a very very hard time trying to use an _unboxed_ vector of strings as in your example.

**Comment by yongqli** [comment]
Right -- good catch. The code still compiled because I asserted `Unbox (v String)`, which just goes to show that all these constraints isn't a good idea.

The String is just an example, I don't actually need to store them for my project.

**Comment by ekmett** [comment]
You could assert `Unbox String` and still compile as well, in an open world, someone could add an instance at any time, so there isn't anything `linear` or anyone else can do about that constraint.

Mind you it isn't _possible_ to write that instance, but the compiler can't know that.

**Comment by ekmett** [comment]
Anyways, you could try to get an instance such as

    instance (Dim n, Unbox a) => Unbox (V n a)

to work for the `Linear.V` module. 

This would get you closer to what you want. 

I'm rather disinclined to make everyone pay an extra indirection for, say, every V4 though. 

i.e. The "V 4" version has to go through an extra pointer indirection to get to the body of the vector, and is much more hazardous to use and code using it is easily screwed up.

You could also rather dramatically reduce your unboxing noise by defining a class using my `constraints` package like this:

```haskell
class Lifts p x where
  lifts :: p a :- p (t a)

instance Lifts Unbox V0 where lifts = Sub Dict
instance Lifts Unbox V1 where lifts = Sub Dict
instance Lifts Unbox V2 where lifts = Sub Dict
instance Lifts Unbox V3 where lifts = Sub Dict
instance Lifts Unbox V4 where lifts = Sub Dict
...
```

Now you can substitute using the `lifts` combinator and your constraint could simplify to:

```haskell
storeInV :: (Applicative v, Lifts Unbox v, Lifts Num v)
         => Int -> (VU.Vector (v Int), VU.Vector (v Double), VU.Vector (v String))
```

There isn't a standard version of such a class, however it might belong in the `constraints` package, perhaps with a more thought out name.

**Comment by yongqli** [comment]
Thanks.

Ideally, `V 4` should switch to become `V4` if the dimension is known at compile time. Is this too much to ask GHC for?


I'm still not sure how to use `lifts`. I get the error:

    Could not deduce (Num (v Int)) arising from the literal ‘1’
    from the context (Applicative v, Lifts Unbox v, Lifts Num v)
      bound by the type signature for
                 storeInV :: (Applicative v, Lifts Unbox v, Lifts Num v) =>
                             Int
                             -> (VU.Vector (v Int), VU.Vector (v Double), VU.Vector (v String))

**Comment by acowley** [comment]
I run into this trouble a lot, but `ConstraintKinds` makes defining an alias for the long constraint work out okay.

**Comment by yongqli** [comment]
I've been using aliases as well, but it still gets unwieldily because you get a combinatorial explosion of `Unbox (v (Int, Double))`, `Unbox (v (Double, Int))`, etc.

I would like to write something like:


    type family IsV (v :: * -> *) :: * -> *
    type instance IsV V0 = V0
    type instance IsV V1 = V1
    type instance IsV V2 = V2
    type instance IsV V3 = V3

    instance (Num a, IsV v) => Num (IsV v a) where

But this of course does not work. Is it possible to get something like this working? I only care about being generic over `V0`, `V1`, `V2`, `V3`, and `V4`.

**Comment by acowley** [comment]
I never figured out how, so I just factored the combinatorial explosion into a handful of aliases that I then combine. It's not pretty, and you do run into maximum tuple sizes eventually if you don't group constraints.

**Comment by yongqli** [comment]
I guess something like this is an option: 

http://stackoverflow.com/questions/28142914/managing-explosion-of-constraints-haskell

**Comment by ekmett** [comment]
To use `lifts` you'd need to apply it in a context using 

```haskell
storeInV :: forall v. (Applicative v, Lifts Unbox v, Lifts Num v) => Int -> (VU.Vector (v Int), VU.Vector (v Double), VU.Vector (v String))
storeInV =  ... 
  \\ (lifts :: Num a :- Num (v a)) 
  \\ (lifts :: Unbox a :- Unbox (v a))
```

To have `v` and `a` refer to the right names you'll need ScopedTypeVariables and to put a `forall` on the outermost signature.

The `V` type I mentioned already exists. I was referring to the existing `Linear.V`, which handles much larger cases as well as 0-4.

**Comment by yongqli** [comment]
Thanks. Is `\\` fast though -- will GHC inline it away or is it a dictionary lookup at run-time? For me, the whole point of using `Linear` is to be really fast for the small vectors my program uses. Thus `Linear.V` seems useless for my use-case since it uses boxed `V.Vector`.

**Comment by ekmett** [comment]
It'll build the dictionary dynamically like any other use scenario where that dictionary gets built. If this code gets inlined, it should inline as well as your old code, and the dictionary would probably get statically constructed.

**Comment by ekmett** [comment]
Closing this as there is an out-of-library solution for the general class of problem mentioned here.
