### ISSUE TITLE
Serialize instances?

### ISSUE THREAD

**Issue by ghorn** [ekmett/linear#66]
How would you feel about a dependency on cereal? I'm currently running into issues with orphan instances. I'm happy to implement this if it's desired.

**Comment by glguy** [comment]
:-1: I'd like to avoid the extra dependency and also to avoid making it harder to deprecate the cereal package

**Comment by ghorn** [comment]
Should I be using something besides cereal?

**Comment by glguy** [comment]
binary has been updated to have all the advantages of cereal for deserialization and cereal's serialization is just an old version of binary's with an extra lazy-to-strict at the end.

**Comment by ghorn** [comment]
Thanks for the info. What are your feeling about Binary instances for linear data?

**Comment by glguy** [comment]
I'm still against the dependency, but it's Edward's call.

**Comment by ekmett** [comment]
I'd be willing to incur a dependency on both, (and `bytes` for that matter) in the interest of killing orphans.

**Comment by ekmett** [comment]
Resolved by 1bc394c

**Comment by ghorn** [comment]
thanks Edward
