### ISSUE TITLE
wrong sign in ortho?

### ISSUE THREAD

**Issue by bflyblue** [ekmett/linear#68]
My math is terrible so I apologize in advance if I'm just confused, but shouldn't the sign of "((f+n)*z))" be flipped?

Perhaps like so:

    ortho' l r b t n f =
      V4 (V4 (-2*x) 0      0      ((r+l)*x))
         (V4 0      (-2*y) 0      ((t+b)*y))
         (V4 0      0      (-2*z) ((f+n)*z))
         (V4 0      0      0      1)
      where x = recip(l-r)
            y = recip(b-t)
            z = recip(f-n)

**Comment by ekmett** [comment]
The sign flip of the z relative to x and y is expected.

Here's the code to Christophe Riccio's `glm::ortho`:

```c++
template <typename valType> 
GLM_FUNC_QUALIFIER detail::tmat4x4<valType> ortho
(
    valType const & left, 
    valType const & right, 
    valType const & bottom, 
    valType const & top, 
    valType const & zNear, 
    valType const & zFar
)
{
    detail::tmat4x4<valType> Result(1);
    Result[0][0] = valType(2) / (right - left);
    Result[1][1] = valType(2) / (top - bottom);
    Result[2][2] = - valType(2) / (zFar - zNear);
    Result[3][0] = - (right + left) / (right - left);
    Result[3][1] = - (top + bottom) / (top - bottom);
    Result[3][2] = - (zFar + zNear) / (zFar - zNear);
    return Result;
}
```

Notice how Result[2][2] has the opposite sign of [0][0] and [1][1].

You'll need to negate all the things, to compare the ortho code in lens with the `glm::ortho` code, and his is column-major, whereas `linear` is row-major, but otherwise they are equivalent.

**Comment by bflyblue** [comment]
What's the expected output of
    ortho 0 1 0 1 0 1 !* V4 1 1 1 1

**Comment by ekmett** [comment]
http://www.songho.ca/opengl/gl_projectionmatrix.html#ortho provides a more detailed derivation that includes the sign flip above.

**Comment by ekmett** [comment]
Keep in mind z coordinates "run the wrong way", and that NDCs run from [-1,1] not [0,1]:

>>> ortho (-1) 1 (-1) 1 1 (-1) !* V4 1 1 1 1
V4 1.0 1.0 1.0 1.0

**Comment by bflyblue** [comment]
Thanks, I'll read through that link carefully to try understand where I'm getting confused. I've been reading the OpenGL SuperBible which has the signed flipped.

    > ortho 0 1 0 1 0 1 !* V4 1 1 1 1
    V4 1.0 1.0 (-3.0) 1.0

with the signed flipped

    > ortho' 0 1 0 1 0 1 !* V4 1 1 1 1
    V4 1.0 1.0 (-1.0) 1.0

I must be going wrong somewhere else with my understanding

**Comment by ekmett** [comment]
Interesting.

**Comment by ekmett** [comment]
I may well have screwed up the set of sign flips I added.

**Comment by bflyblue** [comment]
Yours does match the link you sent

**Comment by bflyblue** [comment]
OpenGL Redbook agrees with you too

**Comment by ekmett** [comment]
OpenGL SuperBible pretty much averages a mistake every few pages, so I'm not terribly surprised that there is a bug in their code. ;)

**Comment by bflyblue** [comment]
One on wikipedia is also the SuperBible way around :( More confused than ever

http://en.wikipedia.org/wiki/Orthographic_projection

**Comment by ekmett** [comment]
? 

The wikipedia article uses the negated term as well.

See the minus sign in the right hand side of the product P = ST = ... and that the product has z with the opposite sign of x and y.

**Comment by bflyblue** [comment]
I'm looking at the (far + near) / (far - near) in the 4th column 3rd row

**Comment by ekmett** [comment]
Let's see:

The code I have now is

```haskell
ortho l r b t n f =
  V4 (V4 (-2*x) 0      0     ((r+l)*x))
     (V4 0      (-2*y) 0     ((t+b)*y))
     (V4 0      0      (2*z) ((f+n)*z))
     (V4 0      0      0     1)
  where x = recip(l-r)
        y = recip(b-t)
        z = recip(n-f)
```

Note `z = recip(n-f) = - recip(f-n)`

So the diagonal z entry is 

```
2*z = 2*recip(n-f) = - 2 / recip (f-n).
```

which matches the wikipedia article.

But the right hand column z entry is

... hrmm ...

```haskell
(f+n)*recip(n-f) = (f+n)/(n-f) = -(f+n)/(f-n)
```

which does indeed appear to have a sign flipped relative to wikipedia.

**Comment by ekmett** [comment]
But then it does match 

    Result[3][2] = - (zFar + zNear) / (zFar - zNear);

from `glm`.

**Comment by bflyblue** [comment]
I'm new to OpenGL but my understanding is Pv should yield NDCs, so I tried some examples using `p = ortho 0 1 0 1 01`:

    p !* V4 0 0 0 1 -- V4 (-1.0) (-1.0) (-1.0) 1.0
    p !* V4 1 1 1 1 -- V4 1.0 1.0 (-3.0) 1.0

Using the wikipedia matrix `p'`:

    p' V4 0 0 0 1 -- V4 (-1.0) (-1.0) 1.0 1.0
    p' V4 1 1 1 1 -- V4 1.0 1.0 (-1.0) 1.0

which is the correct bounds for the NDCs

**Comment by ekmett** [comment]
There has always been a weird sign flip in the `glOrtho` definition.

Notice the documentation in:

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/glOrtho.3.html

which matches the matrix given here, and the fact that the near/far terms are negated when describing the NDCs they map to.

**Comment by ekmett** [comment]
I think the discrepancy is that glOrtho did things in an ass backwards way back in the day, and there is now two different views of how to do this. One that wants `n` and `f` to be used directly as the clip and the other which uses `-n`, and `-f` as the clip planes.

If you negate `n` and `f` before feeding them into ortho, you get the coordinates you expect.

```haskell
>>> let p' = ortho 0 1 0 1 0 (-1)
>>> p' !* V4 1 1 1 1
V4 1.0 1.0 1.0 1.0
```

This is what I meant above when I referred to the fact that you should

> "Keep in mind z coordinates "run the wrong way"

It is kind of a dumb convention, but it matches up with the OpenGL calls that we're mimicking.

**Comment by bflyblue** [comment]
*penny drop* Thank you for being so patient with me!

**Comment by ekmett** [comment]
No problem. It is good to have this worked through on the issues page, so that when the next person comes along with a question, we can address it. =)

Also, it probably makes sense to improve the documentation for ortho to indicate that the `n` and `f` parameters are negated, to match with `glOrtho`.

**Comment by ekmett** [comment]
I've added some documentation to ortho to note the strange handling of the `n` and `f` parameters, and provided a couple of silly examples to demonstrate how the mapping behaves.
