### ISSUE TITLE
Linear.V.int defined conditionally, exported always

### ISSUE THREAD

**Issue by mgomezch** [ekmett/linear#76]
The definition for `int` in `Linear.V` is within

    #if !(MIN_VERSION_reflection(1,3,0))

yet it is unconditionally present in the export list, which yields

    src/Linear/V.hs:37:5:
        Not in scope: ‘int’

**Comment by ekmett** [comment]
what version of reflection are you actually using?

**Comment by ekmett** [comment]
The intention of the export is that it should re-export the definition from more recent versions of `reflection`, but apparently there is some more recent version for which that falls through the holes?

**Comment by mgomezch** [comment]
I’m using `reflection` 1.5.1.2, but with the `-th` flag as I’m cross-compiling for iOS.  `int` and `nat` are not exported from `reflection` when built with that flag.  I suppose this could be solved by testing whether `reflection` was built with the `th` flag, if that’s possible with CPP.

**Comment by ekmett** [comment]
We can't detect the flag. We could offer a similar "unsupported" flag in `linear`, however. If you are building that with a flag, building linear with a similar flag shouldn't be an undue burden.

**Comment by mgomezch** [comment]
Ah, that’s a shame — although I suppose it’s a good thing for the ecosystem in general that CPP can’t be made aware of flags!

I’ve personally already worked around it by manually editing the source, but a similar flag could be cleaner.  Anyone avoiding TH will run into this, so it might be a good idea to give it a similar name: cross-compilation documentation specifically suggests to look out for flags that disable TH.
