### ISSUE TITLE
Matrix inversion check is too aggressive

### ISSUE THREAD

**Issue by yongqli** [ekmett/linear#79]
Linear> inv44 $ V4 (V4 9.99000999000999e-4 0.0 0.0 0.0) (V4 0.0 9.99000999000999e-4 0.0 0.0) (V4 0.0 0.0 9.99000999000999e-4 0.0) (V4 0.0 0.0 0.0 9.99000999000999e-4)
    Nothing

The inverse is of course just a diagonal matrix of `1001`s.

**Comment by yongqli** [comment]
Works fine for `V3`:

    inv33 $ V3 (V3 9.99000999000999e-4 0.0 0.0) (V3 0.0 9.99000999000999e-4 0.0) (V3 0.0 0.0 9.99000999000999e-4)

gives 

    Just (V3 (V3 1001.0 0.0 0.0) (V3 0.0 1001.0 0.0) (V3 0.0 0.0 1001.0))

**Comment by ekmett** [comment]
I'm tempted to remove the check entirely and let it blow up with NaNs.

**Comment by davidsd** [comment]
I would appreciate this change as well. I've been working with matrices of `Rational`s, which have no `Epsilon Rational` or `Floating Rational` instance. Everything else works beautifully, but I've had to just re-implement matrix inversion. I suspect the correct way to deal with zero determinant varies enough over different problem domains that it's best left to the user.

**Comment by ekmett** [comment]
Sounds good. Making the change.
