### ISSUE TITLE
Add function to create diagonal matrix

### ISSUE THREAD

**Issue by yongqli** [ekmett/linear#80]
E.g:

    {-# INLINE diag #-}
    diag44 (V4 a b c d) =
      V4 (V4 a 0 0 0)
         (V4 0 b 0 0)
         (V4 0 0 c 0)
         (V4 0 0 0 d)

**Comment by ekmett** [comment]
We could update Linear.Trace.diagonal to be a lens to the `diagonal` instead of just `join`.

Then it could be used with something like `zero & diagonal .~ V4 a b c d`

**Comment by glguy** [comment]
Is this what you're looking for?

    Linear.Vector.scaled :: (Traversable t, Num a) => t a -> t (t a)
    -- ^ Produce a diagonal (scale) matrix from a vector.

**Comment by ekmett** [comment]
There you go.
