### ISSUE TITLE
Minor doc fix

### ISSUE THREAD

**Issue by peterson** [ekmett/linear#83]
Line 136 of Vector.hs currently reads:
```
  -- >>> V2 4 5 - V2 3 1
```

I think it should read:
```
  -- >>> V2 4 5 ^-^ V2 3 1
```

Is that right? .. I'm sorry also if this is too-minor an issue to report .. just noticed it while reviewing the code!

**Comment by ekmett** [comment]
Both should actually work. There is a Num instance on V2.

**Comment by peterson** [comment]
No worries .. as it was the doc comment for the actual operator ```(^-^)``` I thought you might want to know. Great package btw- I'm learning heaps looking through it!

**Comment by ekmett** [comment]
Being in the haddocks for (^-^) it probably should be the other operator then. =)
