### ISSUE TITLE
1.20.4 build fail

### ISSUE THREAD

**Issue by Nesterov-Konstantin** [ekmett/linear#97]
> Failed to install linear-1.20.4
`eq1' is not a (visible) method of class `Eq1'
 src\Linear\V0.hs:319:25:
    `compare1' is not a (visible) method of class `Ord1'
src\Linear\V0.hs:320:25:
    `showsPrec1' is not a (visible) method of class `Show1'
src\Linear\V0.hs:321:25:
    `readsPrec1' is not a (visible) method of class `Read1'

**Comment by bergey** [comment]
Already fixed in 4a2aab7e873fb25373560f3cbe2f4160546e9294, not yet on Hackage.  In the meantime, use `transformers > 0.3` or `transformers-compat < 0.5`

**Comment by Nesterov-Konstantin** [comment]
sorry, did not notice :)

**Comment by gbaz** [comment]
@bergey then shouldn't someone update the bounds on linear on hackage to reflect this?

**Comment by ekmett** [comment]
Indeed we should.

**Comment by glguy** [comment]
This appears fixed between the release of 1.20.5 and metadata updates
